version: "3.2"
services:

  frontend:
    build: ./frontend
    image: "${APP}_frontend:${TAG}"
    ports:
      - 80:80
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /public
        read_only: true
    networks:
      - backend

  backend:
    build: ./backend
    image: "${APP}_backend:${TAG}"
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /work/public
        read_only: false
    networks:
      - backend

networks:
  backend:
volumes:
  PUBLIC_DIR:
